### PR TITLE
Fix missing coloured kitchen cabinets

### PR DESCRIPTION
**Pull request by monk-afk**
Addresses cabinets missing in issues #4 and #41 

image

Coloured cabinets are craftable after applying patch,
image
image

### CODE REVIEW

**Review by wsor4035 — CHANGES_REQUESTED** [review]
this registration should be next to the node def, not buried here since its for the one specific node

**Comment by monk-afk** [comment]
Understood and applied.

I would like to add, having the unifieddyes registration within the homedecor_common/register.lua file could be useful to fix the ordering of recipe outputs of those with the ud_param2_colorable group.

**Comment by wsor4035** [comment]
not sure why your overriding the method, instead of just calling the crafting function itself

**Comment by monk-afk** [comment]
It's a temporary override. After the cabinets are registered, it gives back the old_homedecor_register function to homedecor.register, and no other items are registered with the override function.

It is to get the cabinet's item names and call unifieddyes.register_color_craft before the cabinets are registered.

I'm not sure how else to get all the different item names and register the color craft before the node craft, short of adding a call to register_color_craft above each node registration.

**Comment by wsor4035** [comment]
there is this loop: https://github.com/mt-mods/homedecor_modpack/blob/master/homedecor_kitchen/init.lua#L164 or homedecor.kitchen_convert_nodes which could be looped over to register the craft

**Comment by monk-afk** [comment]
`homedecor.kitchen_convert_nodes` is a table populated with the nodes after they are registered.

Maybe moving the table insertions before the cabinet_materials traversal would work.

I'll giver a shot and see

**Comment by monk-afk** [comment]
I'm sorry, there is no way to accomplish your request.

**Pull request closed without merging**
