### PR TITLE
add cottages recipes only when cottages is available

### PR DESCRIPTION
**Pull request by Niklp09**

### CODE REVIEW

**Comment by wsor4035** [comment]
what is the point of this? minetest engine lets you register crafts of items that arent present, and almost all inventory mods just ignore crafting recipes that require items that dont exist.

**Comment by Niklp09** [comment]
I thought it would be smart to only register recipes for mods that are actually turned on. See it as "cleanup"

**Comment by BuckarooBanzay** [comment]
> what is the point of this? minetest engine lets you register crafts of items that arent present, and almost all inventory mods just ignore crafting recipes that require items that dont exist.

IMO: why register a recipe if you can't use it, the "cleanup" here is justified if you ask me :shrug:

**Comment by Niklp09** [comment]
reopen?

**Comment by wsor4035** [comment]
> > what is the point of this? minetest engine lets you register crafts of items that arent present, and almost all inventory mods just ignore crafting recipes that require items that dont exist.
> 
> IMO: why register a recipe if you can't use it, the "cleanup" here is justified if you ask me :shrug: 

Why not? Anyways, it's less checking you have to do and allows mods to alias items to those crafts if cottages isn't present to have the crafts work. Otherwise your reimplementing all the crafts in your mod. This is semi common. So in fact this pr code be a breaking change

**Comment by debagos** [comment]
> it's less checking you have to do

Don't you have to do one check anyway to see if you have to register the alias or not?

**Comment by S-S-X** [comment]
I do think it is often better to check mods for crafting but can see what wsor is telling: registering crafts blindly allows less strict use of those crafts through mods named differently as long as items are provided.

> > it's less checking you have to do
> 
> Don't you have to do one check anyway to see if you have to register the alias or not?

Not responsibility here, aliases are registered elsewhere.

**Pull request closed without merging**
